language: csharp
mono: none
dotnet: 2.1.402
sudo: required
git:
  depth: 3
jobs:
  include:
    - stage: run tests
    - script: dotnet test src/Nethermind/Nethermind.KeyStore.Test
      name: "Nethermind.KeyStore.Test"
